"""empty message

Revision ID: a9db6d0cc7bf
Revises: 8911ed90b093
Create Date: 2021-05-19 23:00:39.944017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9db6d0cc7bf'
down_revision = '8911ed90b093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_genre_venueID_fkey', 'artist_genre', type_='foreignkey')
    op.drop_column('artist_genre', 'venueID')
    op.drop_constraint('venue_genre_venueID_fkey', 'venue_genre', type_='foreignkey')
    op.drop_column('venue_genre', 'venueID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue_genre', sa.Column('venueID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('venue_genre_venueID_fkey', 'venue_genre', 'venues', ['venueID'], ['id'])
    op.add_column('artist_genre', sa.Column('venueID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('artist_genre_venueID_fkey', 'artist_genre', 'artists', ['venueID'], ['id'])
    # ### end Alembic commands ###
